### PR TITLE
Remove unneeded paramter in CS_DropWeapon

### PR DESCRIPTION
**Pull request by PerfectLaugh**
Updated in 4/30/2019 csgo update

### CODE REVIEW

**Comment by PerfectLaugh** [comment]
Please merge this pull request to merge 1.9

**Comment by psychonic** [comment]
It will get merged after the master branch build is confirmed to be working (and after the gamedata changes are also merged to 1.9-dev). Right now, the master build is failing.

**Comment by PerfectLaugh** [comment]
master branch has crashed at the start of srcds

**Comment by psychonic** [comment]
The changes from the related PR are not in the master branch builds yet. The latest ones failed. https://builds.alliedmods.net/sm/waterfall

**Comment by PerfectLaugh** [comment]
but that crash happened before the pull request

**Comment by PerfectLaugh** [comment]
idk what happened but I use modified cstrike extension on 6392 of sm 1.10 dlls
https://github.com/alliedmodders/sourcemod/tree/318b36cdcfd852774d9e3ca1178e7ae

**Comment by PerfectLaugh** [comment]
Close due to 1.9 merged

**Pull request closed without merging**
