### PR TITLE
Update MersenneTwister.h

### PR DESCRIPTION
**Pull request by wanted241**
Update MersenneTwister.h

### CODE REVIEW

**Comment by Headline** [comment]
What’s the motivation for this patch?

**Comment by wanted241** [comment]
@Headline I by myself always prefer fresh and new products over the older ones. This is fresh and new. (Can't say it's very very new, but it's just fresher than what SM using right now.)

**Comment by wanted241** [comment]
And better, I guess.

**Comment by wanted241** [comment]
I think this should improve Randomize in Source Mod, since the code is only gets better.

**Comment by KyleSanderson** [comment]
Yeah, unfortunately at this time despite there being a couple (unverified) sources online for a 1.1 update there's no inclination for us to change our rng as there's no documented defect for this one. Nothing on you, please don't let this be a preclusion to you contributing in the future. At this time as there's no documented issues with this rls of Mersenne Twister so we're going to stick it out.

**Pull request closed without merging**
