### PR TITLE
Update sourcepawn submodule

### PR DESCRIPTION
**Pull request by tsuza**
The error reported in https://github.com/alliedmodders/sourcemod/issues/2145 has been fixed in https://github.com/alliedmodders/sourcepawn/commit/9594f99766f9326f336a0307e1887e1317f18b48. 
This PR just updates the submodule to the latest remote commit ( I have not personally compiled & tested it ).

### CODE REVIEW

**Review by dvander — APPROVED** [review]

**Comment by dvander** [comment]
Looks like there are some build errors, I'll try to address those in SP this week.

**Comment by dvander** [comment]
Oh, you just need to bump the AMTL version in your PR. That should fix it.

**Comment by tsuza** [comment]
Sorry for the late commit. I hadn't realized that you had responded until now.

**Comment by tsuza** [comment]
The mock test is failing due to it using "any". If we were to change it to "int", it'd compile & correctly sort the array.

However, I've noticed that the with the latest spcomp the plugin prints gibberish.
image (87)

**Comment by dvander** [comment]
Looks like there is definitely some kind of breakage here, I'll take a look.

**Comment by dvander** [comment]
Sorry this took so long. This was a real bug, that is now fixed on master. To move this PR forward, you should just need to:

(1) Bring sourcepawn to the latest changeset (08d4d0c8b0a54d5778a643c6e16e1cd5b093bcc6) and then make your suggested change to sorting.inc (changing the "int" parameter to "any" for SortCustom1D).

**Comment by tsuza** [comment]
No worries.

I accidentally committed a wrong fix to test_sorting that I made as a test a while ago, which I've reverted.

I've applied the fix to `sorting.inc`. Though, shouldn't we also update
https://github.com/alliedmodders/sourcemod/blob/758714f4241204c4e0feed2cedeffda78ed3c5b8/plugins/include/sorting.inc#L98 and https://github.com/alliedmodders/sourcemod/blob/758714f4241204c4e0feed2cedeffda78ed3c5b8/plugins/include/sorting.inc#L122-L126?

**Comment by dvander** [comment]
Yeah, it should probably be updated as well.

**Comment by tsuza** [comment]
Done 👍

**Pull request merged**
