### PR TITLE
Fix issue #1670

### PR DESCRIPTION
**Pull request by naydef**
Out-of-bounds write
    Not tested If it actually fixes the issue the [issue](https://github.com/alliedmodders/sourcemod/issues/1670) reporter actually
    experiences...
    Not sure why there are other changes written. Probably line endings

### CODE REVIEW

**Comment by dvander** [comment]
Did line endings change or something? There's a lot of noise in this patch.

**Comment by naydef** [comment]
Yea, probably line endings. I'm not sure how change the file without my editor doing all of the other changes
Probably will try with hex editor :)

**Comment by naydef** [comment]
Will try again

**Comment by UnrealKaraulov** [comment]
@naydef I tried to change file via GitHub web editor, and got same problem))))

**Pull request closed without merging**
