### PR TITLE
Update CS:GO gamedata.

### PR DESCRIPTION
**Pull request by Drifter321**

### CODE REVIEW

**Comment by Benoist3012** [comment]
Before merging I think we should consider what has been said on #868 , make the signature longer and wildcard that byte. That's second time it broke now and on the same byte.

**Comment by Headline** [comment]
@Benoist3012 unfortunately that can't be done due to the nearly identical function below, any wild carding will match both

**Comment by Drifter321** [comment]
The byte that changed is the offset that is used for getclantag native. This insures nothing weird changed in the function. Also, as mentioned on windows this is inline strcpy so it can match others.

**Comment by Benoist3012** [comment]
So I get that making it longer is impossible? And I guess trying to replicate the function is a dead end.

**Pull request merged**
