### PR TITLE
Fix GetSteamAccountID validation opt-out

### LINKED ISSUE #1157: GetSteamAccountID(client, false) returns 0 when GetClientAuthId(client, AuthId_Steam3, steamid, sizeof(steamid), false); returns a non-zero number
As explained in the title, I am setting verify to false for both functions. But GetSteamAccountID returns 0 for unverified clients while GetClientAuthId returns a non zero value.

> liljimy100<3297><STEAM_ID_PENDING><> GetSteamAccountID was 0. GetClientAuthId [U:1:999357900]

### PR DESCRIPTION
**Pull request by bottiger1**
pass validated parameter to GetSteamId. Fixes #1157.

### CODE REVIEW

**Comment by asherkin** [comment]
Have you tested that this change does actually fix the issue?

**Comment by bottiger1** [comment]
There doesn't seem to be any issues with it, but I am not sure how I am supposed to reproduce the Steam servers being down.

**Comment by Kenzzer** [comment]
If you have a local server, unplug your Ethernet cable/Disable wifi.

**Comment by bottiger1** [comment]
@asherkin I tested this yesterday during steam maintenance and it appears to work

**Pull request merged**
