### PR TITLE
Set Variables at Initialization

### PR DESCRIPTION
**Pull request by stickz**

### CODE REVIEW

**Comment by psychonic** [comment]
This is, at best, making the code less readable, and at most, accomplishing nothing.

An improvement to the original here here would be to replace those magic numbers with meaningful symbols, as at a glance, it's impossible to tell what the code is doing anyway.

**Comment by stickz** [comment]
The binary size of the plugin is less when compiled. And the initialization stage of the variable isn't wasted by having no initializer. Plus it's consistent with other blocks of code; which, use this better method for setting the value of a variable.

**Comment by asherkin** [comment]
> The binary size of the plugin is less when compiled. And the initialization stage of the variable isn't wasted by having no initializer.

A ternary expression can not be a constant initializer (due to not being constant), it'll compile to identical bytecode.

**Comment by stickz** [comment]
I ran it through the compiler and the size was one byte less.

**Pull request closed without merging**
