### PR TITLE
Update sourcepawn submodule

### PR DESCRIPTION
**Pull request by asherkin**
Spcomp cleanups, debugger API bits, and extra info for crash dumps.

### CODE REVIEW

**Comment by asherkin** [comment]
On the other hand, maybe not, `spcomp` appears to be broken.

```
Program received signal SIGSEGV, Segmentation fault.
0xf7d33ddc in __memcpy_sse2_unaligned () from /usr/lib/libc.so.6
(gdb) bt
#0  0xf7d33ddc in __memcpy_sse2_unaligned () from /usr/lib/libc.so.6
#1  0x0807b8af in pstructs_addarg(pstruct_t*, structarg_t const*) ()
#2  0x0804f975 in declstruct() ()
#3  0x0804c5ee in parse() ()
#4  0x0804a59f in pc_compile(int, char**) ()
#5  0x08049d44 in main ()
```

**Comment by dvander** [comment]
Thanks, I've fixed this in master.

**Comment by asherkin** [comment]
This builds fine locally on Windows, no idea what AppVeyor's problem is.

**Comment by Headline** [comment]
Outdated. A newer pin has landed.

**Pull request closed without merging**
