### PR TITLE
Download Clang from SourceMod site

### PR DESCRIPTION
**Pull request by asherkin**

### CODE REVIEW

**Comment by asherkin** [comment]
(PR to test Travis build)

**Comment by asherkin** [comment]
@psychonic The world is green. :shipit:?

**Comment by psychonic** [comment]
Doooooo it.

**Comment by KyleSanderson** [comment]
Just on this, the cache can (or could only) be invalidated by installing their Ruby suite. I was seeing build issues with it being in a potentially corrupted state which is why I pulled caching from the container merge.

**Pull request merged**
