### PR TITLE
fix 64 bit crash on large gamedata files

### PR DESCRIPTION
**Pull request by bottiger1**
As explained here, there was a crash here caused by parsing a large gamedata file on 64 bits (it doesn't crash on 32 bits). It was fixed by changing the line endings from windows to linux.

https://github.com/alliedmodders/sourcemod/issues/2172

Increasing a buffer size fixes the issue so the line ending change isn't needed. I suspect there's probably some pointer math error that is avoided when the buffer is large enough.

### CODE REVIEW

**Comment by asherkin** [comment]
I think what you're seeing there happens when a read chunk starts exactly on a double quote. Increasing the buffer size would paper over it for your specific input file only.

I think the correct fix is to keep the previous character in a variable for the escape character check, rather than attempting to read backwards from the pointer. The other easy option would be overlapping the reads.

**Comment by peace-maker** [comment]
It looks like unrelated updates to amtl and sourcepawn submodules found their way in here. Is this intentional?

**Comment by bottiger1** [comment]
no it's not intentional. I had to shuffle a lot of stuff around since my pull requests needed to make 64 bit not crash aren't getting merged and I have to update amtl and sourcemod as well.

**Review by psychonic — APPROVED** [review]

**Comment by psychonic** [comment]
Thanks

**Pull request merged**
