### PR TITLE
Actually add spacing to compile.sh

### PR DESCRIPTION
**Pull request by 50Wliu**
The only "confusing" part now is that extra newline between the copyright and header size.

Formatting has also been updated to match the majority of the file (no `;`).

Some output (ignore the fact that I'm using 1.5.1-this is a testing directory just to make sure things compile):
>Compiling basechat.sp ...
SourcePawn Compiler 1.5.1
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC

>Header size:           3044 bytes
Code size:            10684 bytes
Data size:             3460 bytes
Stack/heap size:      16384 bytes; Total requirements:   33572 bytes

>Compiling basecomm.sp ...
SourcePawn Compiler 1.5.1
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC

>Header size:           4296 bytes
Code size:            17004 bytes
Data size:             4976 bytes
Stack/heap size:      16384 bytes; Total requirements:   42660 bytes

>Compiling basecommands.sp ...
SourcePawn Compiler 1.5.1
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC

>Header size:           4884 bytes
Code size:            20308 bytes
Data size:             5220 bytes
Stack/heap size:      16384 bytes; Total requirements:   46796 bytes

>Compiling basetriggers.sp ...
SourcePawn Compiler 1.5.1
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC

>Header size:           3300 bytes
Code size:             9980 bytes
Data size:             2876 bytes
Stack/heap size:      16384 bytes; Total requirements:   32540 bytes

### CODE REVIEW

**Comment by 50Wliu** [comment]
Back from the dead!
I've just added another commit that gets rid of the `RETVAL` stuff while maintaining the same functionality.  Tested this time using multiple scenarios:
* One file
* One broken file
* Multiple files with one in the middle broken

The newline changes in the first commit also seem to fix a bug where if there were errors, the shell prompt would be on the same line as the last line of the script output (eg `4 errorsusername@some-desktop:`)

**Comment by KyleSanderson** [comment]
The formatting is fine, but we shouldn't change behaviour. At the moment it looks like it will continue onwards if a plugin in the middle fails due to that Reteval change.

**Comment by asherkin** [comment]
The shebang change is meant to cover that, but I don't think that is a reliable way of changing the behaviour flags.

**Comment by 50Wliu** [comment]
@asherkin could you clarify?

**Comment by 50Wliu** [comment]
@KyleSanderson Can I ask why you closed this PR?  I'd be happy to make changes if you told me what to do.

**Comment by 50Wliu** [comment]
@KyleSanderson Again, can I ask for the reasoning behind the closing of this PR?

**Comment by KyleSanderson** [comment]
@50Wliu this PR is over two years old, with no movement seen for over a year. This is why the PR was closed. People now rely on specific shipped behaviour, adding pausing, spacing, or anything else relying on shell specific behaviour isn't feasible anymore.

**Pull request merged**
