### PR TITLE
Added stock function `RemoveAllWhitespace`

### PR DESCRIPTION
**Pull request by assyrianic**
`TrimString` doesn't handle space between glyphs.

### CODE REVIEW

**Comment by dvander** [comment]
"Whitespace" is one word, so should be capitalized as if it were one word. To differentiate from TrimString, "RemoveAllWhitespace" would be a better name.

**Comment by KyleSanderson** [comment]
Regex is likely the better approach here?

**Comment by assyrianic** [comment]
> "Whitespace" is one word, so should be capitalized as if it were one word. To differentiate from TrimString, "RemoveAllWhitespace" would be a better name.

agreed, done!

**Comment by peace-maker** [comment]
Cool, this needs documentation in a comment like the other stocks though!

**Comment by assyrianic** [comment]
> Cool, this needs documentation in a comment like the other stocks though!

done!

**Comment by assyrianic** [comment]
I changed the stock so that it'd return the length of the modified string. If it was not modified, the length should be the original length.

**Comment by assyrianic** [comment]
Was thinking of adding another stock where it just removes a singular character:

```c
stock int RemoveAllOfChar(char[] str, int chr)
{
	int j;
	for (int i=0; str[i] != 0; i++)
	{
		if (str[i] != chr)
		{
			str[j++] = str[i];
		}
	}
	str[j] = 0;
	return j;
}
```

**Comment by Fyren** [comment]
There's nothing wrong with the implementation here, but this is also probably too narrow.  I don't see evidence of this being a pain point looking through the forum or Discord.

**Comment by assyrianic** [comment]
> 

Perhaps something like this?
```cpp
stock int TrimChars(char[] str, const char[] chrs)
{
	int j = 0;
	for (int i=0; str[i] != 0; i++)
	{
		bool is_chr = false;
		for (int n=0; chrs[n] != 0; n++)
		{
			is_chr = str[i]==chrs[n] || is_chr;
		}
		if (!is_chr)
		{
			str[j] = str[i];
			j++;
		}
	}
	str[j] = 0;
	return j;
}
```

**Pull request closed without merging**
