### PR TITLE
Fix broken libraries with the SteamWorks SDK (CS:GO)

### PR DESCRIPTION
**Pull request by Wend4r**
These changes fix the malfunction of libraries working with the SteamWorks SDK. For example, https://github.com/KyleSanderson/SteamWorks

After changes #614

Co-Authored-By: @komashchenko

### CODE REVIEW

**Comment by DaLLuZZ** [comment]
Yes, it fixes some issues with steamworks ext

**Comment by Wend4r** [comment]
For Windows, `hl2sdk-csgo\lib\public\steam_api.lib` does not contain links on
```
__imp__SteamAPI_SteamGameServer_v013
__imp__SteamAPI_ISteamGameServer_SetKeyValue
```

I'll go take a look at `hl2sdk-csgo`

**Comment by asherkin** [comment]
What is the issue with SteamWorks.ext and the existing code?

**Comment by DaLLuZZ** [comment]
> What is the issue with SteamWorks.ext and the existing code?

`FixSteam()` doesn't return correct `g_pSteamClientGameServer`

**Comment by asherkin** [comment]
So the code in SM doesn't work when SteamWorks.ext is loaded? Or does the code in SM break SteamWorks.ext?

The bug report template is super useful for this reason.

**Comment by DaLLuZZ** [comment]
The code in SM break https://github.com/KyleSanderson/SteamWorks/blob/e51d2be1ffb0a0064afa6182b0bfea34c94cdc0e/Extension/swgameserver.cpp#L62

```cpp
if (g_pSteamClientGameServer != NULL)
		return g_pSteamClientGameServer;
```
`g_pSteamClientGameServer` is not null cause of SM code in FixSteam(), but it is also incorrect

**Review by asherkin — APPROVED** [review]
Thanks!

**Pull request merged**
