### PR TITLE
Update CS:GO CSWeaponDropBB signatures

### PR DESCRIPTION
**Pull request by Technoblazed**
Fixes gamedata changes from the 4/30/19 CS:GO update. Found by rachnus in the sm discord.

### CODE REVIEW

**Comment by TheExtr1m** [comment]
Hello. These signatures do not work, just updated on their SM server and does not work.

**Comment by Fohdeesha** [comment]
Same issue as TheExtr1m, with these new signatures I'm still getting errors such as the below: 

`SM] Exception reported: Failed to lookup CSWeaponDropBB signature.`

**Comment by Ayuto** [comment]
This PR actually hasn't changed the signatures at all (except removing the byte 56, but that is still a valid part of the signature. It's just not required to find a unique match). The first 6 bytes (2A) are just placeholders. SM's signature scanner ignores/skips them. I guess that has been done to still be able to find the signature even if the function has been hooked by a different server plugin.

It seems like the Windows signature is unchanged. The new Linux signature is:
``55 89 E5 56 53 83 EC 70 8B 5D 08 0F B6 75 10``

**Comment by psychonic** [comment]
@Ayuto thanks. Fixing it up now.

**Pull request merged**
