### PR TITLE
FIx some TF2 natives not having the correct vstk size.

### PR DESCRIPTION
**Pull request by Drifter321**
The vstk for some of the function calls is missing some of the sizes of some of the params. I think this is a bug as far as I know everything else has the size of all params.

### CODE REVIEW

**Comment by KyleSanderson** [comment]
>FIx

r=me

**Comment by Fyren** [comment]
The comments for the signatures of the functions being called should either be updated or removed.

**Comment by psychonic** [comment]
I concur.

**Comment by Drifter321** [comment]
Good catch, I didn't notice the function signature comments.

**Comment by Drifter321** [comment]
Its the new comma

**Pull request merged**
