### PR TITLE
Enable math functions in sqlite

### PR DESCRIPTION
**Pull request by rtldg**
I'd like to use `POW` in sqlite please... (and also have this in 1.11) (also I didn't test this but this this should:tm: work)

### CODE REVIEW

**Comment by peace-maker** [comment]
Please report back once you had time to test this change!

**Comment by rtldg** [comment]
Just now tested on Windows and it worked fine. The github actions should upload assets imo

**Comment by rtldg** [comment]
```
#include <sourcemod>

public void OnPluginStart()
{
	char error[256];
	Database db = SQL_DefConnect(error, sizeof(error));
	PrintToServer("%s", error);
	DBResultSet query = SQL_Query(db, "SELECT POW(5, 2);");
	query.FetchRow();
	PrintToServer("%f", query.FetchFloat(0));
}
```

**Review by peace-maker — APPROVED** [review]
The math functions were added in sqlite 3.35.0 and appear useful. I'm not sure moving business logic into sqlite is a good idea and postgres seems like a better choice if you really want to. But why not have sin/tan in a query?

**Pull request merged**
