### PR TITLE
Fix up gamedata CRC functionality

### PR DESCRIPTION
**Pull request by psychonic**
- Changes the CRC implementation to match what appears to be most other popular implementations.
- Fixes server bin name lookup, broken for most engines.

### CODE REVIEW

**Review by peace-maker — APPROVED** [review]

**Comment by asherkin** [comment]
With the CRC impl change, do we want a different gamedata key so we don't break old versions? Or just avoid using it for a few years?

**Comment by peace-maker** [comment]
Since this was undocumented ever since, we could just say it's a "new" feature. You're required to update to a newer SourceMod build to use it. It's partially broken due to the hardcoded server.so path on older versions anyway and nobody complained, which seems to be a good indicator, that this isn't used anywhere.

**Comment by asherkin** [comment]
I guess as long as we're always restricting the "old" gamedata rather than the "new" gamedata that does work!

**Comment by psychonic** [comment]
> I guess as long as we're always restricting the "old" gamedata rather than the "new" gamedata that does work!

I think that's the only way we'd plan to use it. That way it's less critical to go back and edit later.

**Review by asherkin — APPROVED** [review]

**Pull request merged**
