### PR TITLE
Added client id to MultiTargetFilter forward.

### PR DESCRIPTION
**Pull request by BotoX**
Add backwards compat stuff maybe? has Capability something ...

### CODE REVIEW

**Comment by peace-maker** [comment]
This looks like a simpler duplicate of #478
A capability could indeed be useful, as mentioned in that other PR. `IShareSys::AddCapabilityProvider`

**Comment by KyleSanderson** [comment]
@asherkin how do you feel about this one?

**Review by peace-maker — APPROVED** [review]

**Comment by KyleSanderson** [comment]
@asherkin this still looks OK to me, WDYT?

**Review by asherkin — APPROVED** [review]
Yep, LGTM

**Review by Headline — APPROVED** [review]

**Pull request merged**
