### PR TITLE
Fixes for OnPlayerTeleport hook for linux and linux64 systems

### PR DESCRIPTION
**Pull request by MrD4rk5oul**
Merge #2214 failed due to pointer misalignment which was fixed in safetyhook and a [revision commit](https://github.com/alliedmodders/sourcemod/commit/4004471d8dde9ae3523cc61cb98b954dee545a41) was made, making the process of hooking work normally again.

Tests were made on Linux with bare MM+SM installations, MM+SM+many dummy plugins using different hooks and both mock and production servers , and no recurring crashes were reported.

Tests were also made on Windows, both with MM+SM installations and MM+SM+dummy hook plugins.

Pull request fixes issue #2140.

### CODE REVIEW

**Review by psychonic — CHANGES_REQUESTED** [review]
Thanks for following up on this! Can we change the gamedata update to instead use a new name for this, leaving the original one as-is? Otherwise, if we push the updated gamedata to the gamedata updater without users necessarily having manually updated SourceMod, there will be a mismatch between what function variant the code is targeting versus what the gamedata is targeting.

**Comment by psychonic** [comment]
> Thanks for following up on this! Can we change the gamedata update to instead use a new name for this, leaving the original one as-is? Otherwise, if we push the updated gamedata to the gamedata updater without users necessarily having manually updated SourceMod, there will be a mismatch between what function variant the code is targeting versus what the gamedata is targeting.

Should also add a comment to note why it was done, noting that the older one can be nuked later.

**Comment by MrD4rk5oul** [comment]
Added a new registry for the teleportation checking and marked the old one as Obsolete.

**Review by psychonic — APPROVED** [review]
That's perfect. Thanks!

**Pull request merged**
