### PR TITLE
Updated 'checkout-deps' to check for 'pip'/'pip3' prior to installing 'AMBuild'.

### LINKED ISSUE #1324: bash sourcemod/tools/checkout-deps.sh fails to run
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Debian 10
  * Game/AppID (with version if applicable): TF2
  * Current SourceMod version: 
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

Trying to download a build environment, checkout-deps.sh throws an error on ambuild2

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named ambuild2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ambuild2'
Cloning into 'ambuild'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 2647 (delta 35), reused 46 (delta 34), pack-reused 2584
Receiving objects: 100% (2647/2647), 1.53 MiB | 8.77 MiB/s, done.
Resolving deltas: 100% (1820/1820), done.
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
Installing AMBuild at the user level. Location can be: ~/.local/bin
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

# Problematic Code (or Steps to Reproduce)
  ```
  // TODO(you): code here to reproduce the problem
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

### PR DESCRIPTION
**Pull request by WildCard65**
## checkout-deps (PowerShell/BASH):
   - Checks for an active 'python'/'python3' command.
   - Checks for an active pip installation in the detected Python installation, otherwise, it installs it via 'get-pip.py'

## checkout-deps.ps1
   - Added fallback to 'py'.

Closes #1324 

See: alliedmodders/ambuild#68

### CODE REVIEW

**Comment by WildCard65** [comment]
Pinging @enderandrew to help test this draft.

**Comment by WildCard65** [comment]
@dvander This should be ready to review, the checkout-deps.sh changes passed on a WSL Ubuntu 20.04 install (And 'python' didn't exist, just 'python3').

PowerShell changes should also work (Though I haven't added support for 'python3' incase anyone uses PowerShell on Ubuntu, should I support that?)

**Comment by WildCard65** [comment]
I forgot @KyleSanderson as well...

**Comment by enderandrew** [comment]
Seems to work for me.

**Comment by WildCard65** [comment]
@enderandrew Make sure to uninstall pip and setuptools as well for testing, on WSL Ubuntu for me, user install of pip worked.

**Comment by WildCard65** [comment]
Adding @Headline to this also.

**Comment by WildCard65** [comment]
Gonna re-open this for a cleaner PR history.

**Pull request closed without merging**
