### PR TITLE
Add new custom kill identifier

### PR DESCRIPTION
**Pull request by 404UNFca**
Adds in `TF_CUSTOM_AXTINGUISHER_BOOSTED`, [seen here in the binary](https://cdn.discordapp.com/attachments/335291251937116167/558420271426699264/unknown.png).

### CODE REVIEW

**Comment by psychonic** [comment]
There's no need to open a new PR for each edit. Just add a new commit to revert the whitespace changes.

**Comment by 404UNFca** [comment]
Apologies, I was a tad rusty with my Githubbing skillz. Realized a little too late that I could've restored the patch-3 branch and fixed it up as the solution occurred to me after submitting this PR.

I'm not entirely certain _how_ to revert the whitespace changes as I didn't touch anything in that area of the file. Just guessing, but perhaps that's a sign that the whitespace in that particular area wasn't the same as the rest of the file? Correct me if I'm wrong of course (I probably am :laughing: )

**Comment by 404UNFca** [comment]
FINALLY fixed the bitch.

**Comment by 404UNFca** [comment]
"Don't forget about me, Headline", this PR cries as it sees Headline commit a spelling fix for the word "runoff".

**Comment by Headline** [comment]
@404UNFca

Well, ones a comment spelling change, and one’s a permanent sdk change
:)

**Pull request merged**
