### PR TITLE
Create new gamedata for event hooking

### PR DESCRIPTION
**Pull request by stickz**
This commit creates a wrapper intended to be used when hooking events. It accounts for differences in the event strings across games. And removes the need for redundantly calling HookEvent(). 

Empires support is coincidentally fixed for `basetriggers `and `funcommands`.

### CODE REVIEW

**Comment by WildCard65** [comment]
sdktools_stocks.inc is generally for stocks related to what SDKTools does, I think the stock would fit right in the halflife.inc or maybe sourcemod.inc

**Comment by stickz** [comment]
Alright, i'm done making changes. Anything else need fixed?

**Comment by KyleSanderson** [comment]
When this is ready for merging let us know.

**Comment by stickz** [comment]
As far as I'm concerned it's ready now. Nothing else has been specified that is required for merging. The wrapper is as light weight as possible. And it's not any harder (from my perspective) to read the plugin code.

**Pull request closed without merging**
