### PR TITLE
Add Support for Direct Arrays into OnMenuVoteResults handler

### PR DESCRIPTION
**Pull request by PerfectLaugh**
Support 1.11 compiled plugins for VoteMenu handlers

### CODE REVIEW

**Comment by dvander** [comment]
Thanks for catching this. I apparently failed to sweep the include files properly for uses of double-arrays.

There is so much complexity here, I think it would be good to move the responsibility over to the VM. It would simplify this a lot. I'll try to do that sometime this week.

**Comment by PerfectLaugh** [comment]
I think it is good enough to keep this situation on.
The core_logic and extension part are still required to using underlying array anyway.
Even we created the API for that operation, extensions that use 2D-Arrays are still requires to modify.

**Comment by dvander** [comment]
They need modification, but this is extremely tricky code that is easy to get wrong. And it doesn't make sense to embed it right into the menu code (which is already very complicated). So I'm happy to do some refactoring to clean this up.

**Comment by dvander** [comment]
I just posted https://github.com/alliedmodders/sourcemod/pull/1643 to fix this, but I'm unable to test at the moment. Any help would be appreciated.

**Comment by PerfectLaugh** [comment]
Closed in favor of #1643

**Pull request closed without merging**
