### PR TITLE
Prevent use of primitive float operation functions

### PR DESCRIPTION
**Pull request by Headline**
Apparently people use the float natives for actual float arithmetic; they're not _really_ intended to be used directly. I've added a note to deter people from using these instead of their respective operators.

### CODE REVIEW

**Comment by asherkin** [comment]
I'd prefer "This native is internal implementation." rather than "This native only exists to be overloaded."

Does adding `#deprecated` work and not carry through to the operators?

**Comment by Headline** [comment]
@asherkin I haven’t tested whether #depreicated will carry through, but depreicated implies removal so I’m not sure if that’s what we’d want to suggest.

**Comment by asherkin** [comment]
We want people to stop using these natives. They are not used internally in modern plugins, the JIT emits float opcodes directly, they're definitely on the removal path if we break binary compat for some reason.

**Comment by Headline** [comment]
The deprecation warning doesn't carry through to the overloads, so `#pragma deprecated` works as we'd want here. I also threw in your edit, thanks!

🚢

**Pull request merged**
