### PR TITLE
Update Brazilian Phrases

### PR DESCRIPTION
**Pull request by crashzk**
https://github.com/orgs/alliedmodders/projects/1/views/1?pane=issue&itemId=24307179

### CODE REVIEW

**Review by psychonic — APPROVED** [review]

**Comment by peace-maker** [comment]
@Tiagoquix Do you have concerns with these changes?

**Comment by crashzk** [comment]
@Tiagoquix I understand your point, in this case it would just be a translation that I already use in my CSGO servers. In any case, I can convert it to leave it translated again as before, in which case I only sent what I already had.

Anyway, as soon as possible I'll update again and leave it in lower case.

AllTalk question, I believe we can leave it translated right then and remove (AllTalk) from the sentence, right?

**Comment by crashzk** [comment]
Done, let me know if I need to change anything else.

**Comment by crashzk** [comment]
Done, all right now, so I believe.

_Note: Leaving the AllTalk message translated and also putting (AllTalk) in the sentence, I believe it applies what you said, translates something and leaves others in English._

**Review by psychonic — APPROVED** [review]

**Pull request merged**
