### PR TITLE
Add nmethod CloseTimerfor timers

### PR DESCRIPTION
**Pull request by s3bul**

### CODE REVIEW

**Comment by asherkin** [comment]
You should use the `delete` keyword from the new syntax in normal use, we don't need an additional stock for the 0.001% of cases where the `autoClose` param is required.

**Comment by s3bul** [comment]
Example of use this method
```sourcepawn
if(timerHandle  != INVALID_HANDLE) CloseTimer(timerHandle);
timerHandle = CreateTimer(0.8, ActionMethod, GetClientSerial(client));
```
so i dont need delete the variable.

**Comment by asherkin** [comment]
delete timerHandle;

will do the same job as

    if (timerHandle != INVALID_HANDLE) {
      KillTimer(timerHandle);
      timerHandle = INVALID_HANDLE;
    }

**Comment by s3bul** [comment]
Ok, i have more learn this sm 1.7 :D

**Pull request closed without merging**
