### PR TITLE
Add TFCond_PowerupModeDominant

### PR DESCRIPTION
**Pull request by Mikusch**

### CODE REVIEW

**Comment by asherkin** [comment]
What is the source of the name and description for this?

**Comment by Mikusch** [comment]
Found in the TF2 binary, name is ``TF_COND_POWERUPMODE_DOMINANT`` (applied in ``CTFPlayer::StartPowerupModeDominant``, can be easily searched for as a string) and it nerfs some of the powerups.

**Review by NiagaraDryGuy — APPROVED** [review]
Good addition

**Review by asherkin — APPROVED** [review]
LGTM, thanks!

**Comment by KyleSanderson** [comment]
Nice one - thank you 😄

**Pull request merged**
