### PR TITLE
Add command sm_dump_datamaps_sorted

### PR DESCRIPTION
**Pull request by 404UNFca**
Dumps all entity datamaps into "tf/datamaps" in individual TXT files named after the entity.

More info here: https://forums.alliedmods.net/showthread.php?t=289713

Changes do indeed work as evidenced by http://www.unfgaming.net/datamaps/tf2

### CODE REVIEW

**Comment by luki1412** [comment]
A great idea!
What about sm_dump_netprops ?

**Comment by 404UserNotFound** [comment]
I didn't make the code (Sigsegv did, a big thanks to him), and I didn't need to individually dump the netprops. But if someone can make a similar command for the other dump types, that'd be nice to have.

**Comment by Deathreus** [comment]
Sorry but this is bugging me, "as at (date)" should be "as of (date)", this isn't about grammatical correctness, it just sounds better

**Comment by 404UserNotFound** [comment]
That grammatical error is in SourceMod by default. I didn't write that.

**Comment by asherkin** [comment]
It's not an error, "as at" is grammatically correct for this usage.

**Comment by Deathreus** [comment]
I wasn't saying it was grammatically incorrect, I specifically stated that

**Comment by FlaminSarge** [comment]
nit: "DumpSingleDataMapToFile", or even just "DumpDataMapToFile", rather than "DumpOne...", might work better. Hell, maybe even "DumpDataMapForClass" or something.

**Comment by 404UserNotFound** [comment]
Get out of my brain! DumpSingleDataMapToFile is the name I used in my local copy where I've been trying to reverse engineer the netprops to dump individually as well. Haven't made much progress though.

**Pull request closed without merging**
