### PR TITLE
Allow sending panels to SourceTV client via settings

### LINKED ISSUE #1563: Sourcemod menus do not show for Source TV (L4D2)
Not compatible apparently.

https://github.com/shqke/sourcetvsupport/issues/24#issuecomment-894728629

### PR DESCRIPTION
**Pull request by A1mDev**
Code tested in game Left4Dead2, menu successfully sent to SourceTV client.

Close #1563 
Related PR #1775

### CODE REVIEW

**Comment by asherkin** [comment]
This seems like too much faff around it, based on the discussion in the previous PR just removing the `pPlayer->IsFakeClient()` check seems good enough? The client index is passed in, I don't think we need an additional param of "yes, I really meant to pass _that_ client index in".

**Comment by A1mDev** [comment]
I think it would be nice to keep the default behavior?

**Comment by A1mDev** [comment]
It's just that the old PR was never accepted and I thought it wasn't worth changing the default behavior, of course I can remove the extra code if you say so.

**Comment by A1mDev** [comment]
Done, I made one check for SourceTV, I don't know if it is needed for other bots, let someone else make a PR if it is needed for ReplayClient.

**Comment by asherkin** [comment]
Presumably nothing breaks if sent to other fake clients? We should err on trusting the plugin that it is doing what it wants.

**Comment by A1mDev** [comment]
Done

**Review by asherkin — APPROVED** [review]
LGTM, @psychonic ?

**Review by psychonic — APPROVED** [review]

**Pull request merged**
