### PR TITLE
Converted NormalSHook to typeset and added old prototype.

### PR DESCRIPTION
**Pull request by psychonic**
New prototype was added in PR #247 

This fixes compilation of plugins that are using pre-1.8 sound hook prototypes.

### CODE REVIEW

**Comment by 50Wliu** [comment]
:green_heart: Thanks so much for this!

Also, shouldn't `clients[64]` be `clients[MAXPLAYERS]` instead?

**Comment by psychonic** [comment]
Unfortunately, no. Much older versions of SM only using an array of size 64. If we increase to 65 here, users compiling against the newer include and (very) old SM will run into an issue where that last index is not valid.

**Comment by psychonic** [comment]
As @VoiDeD pointed out to me yesterday, that's actually probably fine (if it can be added as a third typeset member), since reading past the numClients was never supported anyway, and that wouldn't have been higher than 64 before (and the plugin wouldn't be able to write more than 64 with the old-sized array).

**Comment by KyleSanderson** [comment]
:shipit:

**Pull request merged**
