### PR TITLE
Add AMBuild2 script to Sample Extension

### PR DESCRIPTION
**Pull request by powerlord**
This adds an AMBuildScript, configure.py, and PackageScript to the Sample Extension.

This is adapted from SourceMod 1.8's AMBuildScript and PackageScript.

This AMBuildScript is also smart enough to notice if smsdk_ext.cpp is located in the project.  This was added for compatibility with SM 1.5 and below extensions.

NOTE:  This always requires MM:S to be present even for non-MMS extensions.  I should probably fix that, but afaict it only affects the include paths.

### CODE REVIEW

**Comment by powerlord** [comment]
Note: I didn't touch the mms_sample_ext while I was working on this.  Does anyone even use that one?

**Comment by asherkin** [comment]
Looks like you've merged the AMBuildScript and AMBuilder files, which makes it much harder for people to update in the future (as new SDKs get added).

**Comment by powerlord** [comment]
@asherkin There, I've split them into separate files.

**Comment by WildCard65** [comment]
You should probably also check for smsdk_ext.cpp in sdk folder

**Comment by powerlord** [comment]
@WildCard65 Oh right, I don't have a copy of 1.5 handy.  I forgot it was in the sdk folder and not the base folder.  I'll fix that shortly.

Actually, I'm going to try to fix some of the comments as well as long as I'm doing another commit.

**Comment by psychonic** [comment]
I won't have time to give this a real look until the weekend, but thanks for doing this! It's been needed for a while.

**Comment by powerlord** [comment]
@psychonic So, did you ever get a chance to look at this?

**Comment by psychonic** [comment]
Let's get this in there. We can always improve on it later if needed.

**Pull request merged**
