### PR TITLE
Add OnLogMessage and OnLogError

### PR DESCRIPTION
**Pull request by DoctorMcKay**
<VoiDeD> you know you can do the PR yourself right
    <McKay> but then I'll get yelled at for your bad code
    <VoiDeD> or you'll get a push started for a better/different implementation

### CODE REVIEW

**Comment by KyleSanderson** [comment]
@DoctorMcKay is this still desired?

**Comment by asherkin** [comment]
I'm not a fan of the ability to suppress the logging (or the SetInForward hack required to support it).

What's the use case for these forwards?

**Comment by DoctorMcKay** [comment]
Yes, this is still desired. My use case is logging stuff to a central database for easy review. 

Ability to suppress provides parity with `OnLogAction`, although it's not terribly important to me.

**Comment by peace-maker** [comment]
I'd rather have people fix bugs than suppressing the error logs!

**Comment by DoctorMcKay** [comment]
Ability to suppress error logs is probably not the best idea, but I don't see any big problems with suppressing regular logs.

**Comment by dvander** [comment]
Yeah I'm confused too. This seems like something asking for trouble. Logging is designed to *not* be suppressed. If users don't want it they can turn it off.

**Comment by VoiDeD** [comment]
The goal (at least for the implementation I needed) was to be able to suppress logging for two reasons: to entirely pipe it somewhere else (mysql, etc), and to add some rate limiting to avoid trashing the disk when plugins spew errors in places such as `OnGameFrame` and friends.

**Comment by dvander** [comment]
Seems like that could just be Core functionality (and SM probs shouldn't be doing main-thread I/O either).

**Comment by KyleSanderson** [comment]
@DoctorMcKay are you able to drive this PR?

**Comment by KyleSanderson** [comment]
The relay portion of this is an excellent idea, but we can't add an API to hide plugin errors from first party logging.

<VoiDeD> fork it -> new branch off logmessage -> make ur commits -> new PR
<McKay> that's about 3 steps beyond my caring point

**Pull request closed without merging**
