### PR TITLE
Seed rand only once

### PR DESCRIPTION
**Pull request by Deathreus**
Light testing applied

### CODE REVIEW

**Comment by Deathreus** [comment]
See [this](https://hatebin.com/jzqjayshrw) for why it is needed

**Review by Headline — APPROVED** [review]
Quite surprised this wasn't discovered earlier - thanks for the patch!

**Comment by peace-maker** [comment]
I'm not sure that `srand` call in core is affecting `rand` calls in `logic`? Might work that way though.

**Comment by asherkin** [comment]
> I'm not sure that `srand` call in core is affecting `rand` calls in `logic`? Might work that way though.

The random seed is thread-local state, so it's shared across all modules in a process.

**Pull request merged**
