### PR TITLE
Expose SourceMods existing Think hook to Pawn

### PR DESCRIPTION
**Pull request by KyleSanderson**
SourceMod utilizes Think instead of GameFrame to enable plugins to load/unload while the server is hibernating. As an unfortunate side effect, these plugins can't do much if anything while the server is hibernating. Exposing a forward is a simple, requested for years, feature that helps server operators keep hibernation enabled while utilizing SourceMod.

### CODE REVIEW

**Comment by peace-maker** [comment]
You might want to add the forward declaration in one of the include files as well :stuck_out_tongue:

**Comment by asherkin** [comment]
You would think you would know our feelings on opening PRs that don't even compile...

**Comment by KyleSanderson** [comment]
This is incomplete, we all use Travis and Appveyor for coverage testing.

**Comment by fakuivan** [comment]
I've been working on this issue for a while. I added a flag for RequestFrame called HookThink. But when I install the build into a clean test server I get "Unable to load extension "sdkhooks.ext": undefined symbol: Warning" and "Unable to load extension "sdktools.ext": undefined symbol: Warning". I am working on the branch, I'll commit when I can.

**Comment by fakuivan** [comment]
[^^](https://github.com/fakuivan/sourcemod/commit/7ed842b0df9766fc573da860144e10e30400a96d?diff=split)

**Pull request closed without merging**
