### PR TITLE
Use MySQL 5.5 for MySQL extension.

### PR DESCRIPTION
**Pull request by psychonic**
@peace-maker Your wildest dream come true.

### CODE REVIEW

**Comment by Bara** [comment]
With which version comes this?

**Comment by asherkin** [comment]
Uh, none, it hasn’t been merged.

**Comment by psychonic** [comment]
On our own buildslaves, we'll be using 5.5.54 on Windows, 5.5.58 on Linux, and 5.5.40 on Mac.

Intentionally not going higher, even in the 5.5 series, to not introduce extra dependencies.

**Comment by Bara** [comment]
Okay good to know, but i mean with which sourcemod version (1.10 or for 1.9 too?). 😖

**Comment by psychonic** [comment]
Undetermined as of yet.

**Comment by Bara** [comment]
but isn't the version for linux 5.6? ( Line: https://github.com/alliedmodders/sourcemod/blob/33c74944ff112b92829cc9006e0231384e139b10/tools/checkout-deps.sh#L55 / https://github.com/alliedmodders/sourcemod/blob/33c74944ff112b92829cc9006e0231384e139b10/tools/checkout-deps.sh#L66 )

**Comment by psychonic** [comment]
No. We don't use checkout-deps in the official builds. The MYSQL55 env var on the slave points to mysql-5.5.58-linux-glibc2.12-i686.

I didn't bother updating checkout-deps for it since it was already at a newer version than we build now (itself a newer one than we were building against before).

Doing self-compiles against 5.6 is fine. We're just keeping the lower one on official builds to not increase the GLIBC version requirement.

**Pull request merged**
