### PR TITLE
Fix CSGO Update crash (11/19/2019)

### PR DESCRIPTION
**Pull request by PerfectLaugh**
We know what happened when Valve do something big.
Not tested on Linux

### CODE REVIEW

**Comment by proobs** [comment]
Tested it on linux, and they work 👍

**Comment by sneak-it** [comment]
Tested first commit's changes, everything works well. RoundRespawn sig is broken still, however.

**Comment by psychonic** [comment]
Thank you! I know this stuff is tedious to find.

Is that all of it?

**Comment by PerfectLaugh** [comment]
I actually don't know. I am using only Windows version and I am too lazy to find Linux x64 version.
Is that necessary?

**Comment by psychonic** [comment]
> Is that necessary?

If they're known to be (likely) wrong, I think that commenting them out would be an improvement over leaving them incorrect. That, or inferring/guessing at the new correct value.

**Comment by PerfectLaugh** [comment]
Hmm I guess I would have to find Linux x64 right away.
I have no Mac version unfortunately

**Comment by Akeno215** [comment]
Tested it on linux :) Works

**Comment by mmendesico** [comment]
Pure server: file [GAME]\pak01_001.vpk does not match the server's file

is my error. :(

**Comment by gonzalopixart** [comment]
With these changes, another problem may be ignored. is that now certain add-ons throw the error: required extension of the file "cstrike" ("games/game.cstrike.ext any possible solution?

**Comment by PerfectLaugh** [comment]
> With these changes, another problem may be ignored. is that now certain add-ons throw the error: required extension of the file "cstrike" ("games/game.cstrike.ext any possible solution?
> 
> logs from my server: advancedresetscore.smx ([CS:GO] Advanced ResetScore plugin): Required extension "cstrike" file("games/game.cstrike.ext") not running
> deathmatch.smx (Deathmatch): Required extension "cstrike" file("games/game.cstrike.ext") not running
> gloves.smx (Gloves): Required extension "cstrike" file("games/game.cstrike.ext") not running
> kento_rankme.smx (RankMe): Required extension "cstrike" file("games/game.cstrike.ext") not running
> multicfg.smx (MultiCFG ): Required extension "cstrike" file("games/game.cstrike.ext") not running
> weapons.smx (Weapons & Knives): Required extension "cstrike" file("games/game.cstrike.ext") not running

Please do "sm exts list" for me

**Comment by gonzalopixart** [comment]
> > With these changes, another problem may be ignored. is that now certain add-ons throw the error: required extension of the file "cstrike" ("games/game.cstrike.ext any possible solution?
> > logs from my server: advancedresetscore.smx ([CS:GO] Advanced ResetScore plugin): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > deathmatch.smx (Deathmatch): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > gloves.smx (Gloves): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > kento_rankme.smx (RankMe): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > multicfg.smx (MultiCFG ): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > weapons.smx (Weapons & Knives): Required extension "cstrike" file("games/game.cstrike.ext") not running
> 
> Please do "sm exts list" for me

      [01] Automatic Updater (1.9.0.6282): Updates SourceMod gamedata files
         [02] Webternet (1.9.0.6282): Extension for interacting with URLs
         [03] <FAILED> file "game.cstrike.ext.2.csgo.dll": Could not read sm-cstrike.games: Section declared with unknown tokens
         [04] BinTools (1.9.0.6282): Low-level C/C++ Calling API
         [05] SDK Tools (1.9.0.6282): Source SDK Tools
         [06] Top Menus (1.9.0.6282): Creates sorted nested menus
         [07] Client Preferences (1.9.0.6282): Saves client preference settings
         [08] SQLite (1.9.0.6282): SQLite Driver
         [09] <OPTIONAL> file "dhooks.ext.dll": No se puede encontrar el mdulo especificado.
         
         [10] SDK Hooks (1.9.0.6282): Source SDK Hooks
         [11] Regex (1.9.0.6282): Provides regex natives for plugins
         [12] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
         [13] GeoIP (1.9.0.6282): Geographical IP information
         [14] PTaH (1.1.0): Additional CS:GO Hooks and Natives
         [15] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI



its my list.

**Comment by PerfectLaugh** [comment]
> > > With these changes, another problem may be ignored. is that now certain add-ons throw the error: required extension of the file "cstrike" ("games/game.cstrike.ext any possible solution?
> > > logs from my server: advancedresetscore.smx ([CS:GO] Advanced ResetScore plugin): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > deathmatch.smx (Deathmatch): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > gloves.smx (Gloves): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > kento_rankme.smx (RankMe): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > multicfg.smx (MultiCFG ): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > weapons.smx (Weapons & Knives): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > 
> > 
> > Please do "sm exts list" for me
> 
> ```
>   [01] Automatic Updater (1.9.0.6282): Updates SourceMod gamedata files
>      [02] Webternet (1.9.0.6282): Extension for interacting with URLs
>      [03] <FAILED> file "game.cstrike.ext.2.csgo.dll": Could not read sm-cstrike.games: Section declared with unknown tokens
>      [04] BinTools (1.9.0.6282): Low-level C/C++ Calling API
>      [05] SDK Tools (1.9.0.6282): Source SDK Tools
>      [06] Top Menus (1.9.0.6282): Creates sorted nested menus
>      [07] Client Preferences (1.9.0.6282): Saves client preference settings
>      [08] SQLite (1.9.0.6282): SQLite Driver
>      [09] <OPTIONAL> file "dhooks.ext.dll": No se puede encontrar el mdulo especificado.
>      
>      [10] SDK Hooks (1.9.0.6282): Source SDK Hooks
>      [11] Regex (1.9.0.6282): Provides regex natives for plugins
>      [12] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
>      [13] GeoIP (1.9.0.6282): Geographical IP information
>      [14] PTaH (1.1.0): Additional CS:GO Hooks and Natives
>      [15] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI
> ```
> 
> its my list.

Your gamedata is invalid. Make sure you copy paste all the files.
Oh. And make sure you disable the gamedata updater temporarily by setting DisableAutoUpdate to yes in core.cfg

**Comment by gonzalopixart** [comment]
> > > > With these changes, another problem may be ignored. is that now certain add-ons throw the error: required extension of the file "cstrike" ("games/game.cstrike.ext any possible solution?
> > > > logs from my server: advancedresetscore.smx ([CS:GO] Advanced ResetScore plugin): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > deathmatch.smx (Deathmatch): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > gloves.smx (Gloves): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > kento_rankme.smx (RankMe): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > multicfg.smx (MultiCFG ): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > weapons.smx (Weapons & Knives): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > 
> > > 
> > > Please do "sm exts list" for me
> > 
> > 
> > ```
> >   [01] Automatic Updater (1.9.0.6282): Updates SourceMod gamedata files
> >      [02] Webternet (1.9.0.6282): Extension for interacting with URLs
> >      [03] <FAILED> file "game.cstrike.ext.2.csgo.dll": Could not read sm-cstrike.games: Section declared with unknown tokens
> >      [04] BinTools (1.9.0.6282): Low-level C/C++ Calling API
> >      [05] SDK Tools (1.9.0.6282): Source SDK Tools
> >      [06] Top Menus (1.9.0.6282): Creates sorted nested menus
> >      [07] Client Preferences (1.9.0.6282): Saves client preference settings
> >      [08] SQLite (1.9.0.6282): SQLite Driver
> >      [09] <OPTIONAL> file "dhooks.ext.dll": No se puede encontrar el mdulo especificado.
> >      
> >      [10] SDK Hooks (1.9.0.6282): Source SDK Hooks
> >      [11] Regex (1.9.0.6282): Provides regex natives for plugins
> >      [12] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
> >      [13] GeoIP (1.9.0.6282): Geographical IP information
> >      [14] PTaH (1.1.0): Additional CS:GO Hooks and Natives
> >      [15] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI
> > ```
> > 
> > 
> > its my list.
> 
> Your gamedata is invalid. Make sure you copy paste all the files.
> Oh. And make sure you disable the gamedata updater temporarily by setting DisableAutoUpdate to yes in core.cfg

Modify only two files engine.csgo.txt, game.csgo.txt and core.cfg the game works. just don't lift the smx. but this does not solve my problem, I execute this "sm exts list" command again ...

REGISTRATION: [01] File <FAILED> "game.cstrike.ext.2.csgo.dll": Could not read sm-cstrike.games: Section declared with unknown tokens
[02] BinTools (1.9.0.6282): C / C ++ low level calling API
[03] SDK Tools (1.9.0.6282): Source SDK Tools
[04] Main menus (1.9.0.6282): Create ordered nested menus
[05] Customer preferences (1.9.0.6282): Save the customer preference settings
[06] SQLite (1.9.0.6282): SQLite driver
[07] <OPTIONAL> file "dhooks.ext.dll": The specified module cannot be found.

[08] SDK Hooks (1.9.0.6282): Source SDK Hooks
[09] Regex (1.9.0.6282): provides regex natives for add-ons
[10] SteamWorks extension (1.2.3): exposes SteamWorks functions to developers
[11] GeoIP (1.9.0.6282): IP geographic information
[12] PTaH (1.1.0): Additional CS: GO Hooks and Natives
[13] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI


the problem persists :(

listing error plugins: Errors:
         advancedresetscore.smx ([CS: GO] Advanced ResetScore plugin): Required extension "cstrike" file ("games / game.cstrike.ext") not running
         deathmatch.smx (Deathmatch): Required extension "cstrike" file ("games / game.cstrike.ext") not running
         gloves.smx (Gloves): Required extension "cstrike" file ("games / game.cstrike.ext") not running
         kento_rankme.smx (RankMe): Required extension "cstrike" file ("games / game.cstrike.ext") not running
         multicfg.smx (MultiCFG): Required extension "cstrike" file ("games / game.cstrike.ext") not running
         weapons.smx (Weapons & Knives): Required extension "cstrike" file ("games / game.cstrike.ext") not running

**Comment by psychonic** [comment]
> 
> 
> > > > > With these changes, another problem may be ignored. is that now certain add-ons throw the error: required extension of the file "cstrike" ("games/game.cstrike.ext any possible solution?
> > > > > logs from my server: advancedresetscore.smx ([CS:GO] Advanced ResetScore plugin): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > deathmatch.smx (Deathmatch): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > gloves.smx (Gloves): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > kento_rankme.smx (RankMe): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > multicfg.smx (MultiCFG ): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > weapons.smx (Weapons & Knives): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > 
> > > > 
> > > > Please do "sm exts list" for me
> > > 
> > > 
> > > ```
> > >   [01] Automatic Updater (1.9.0.6282): Updates SourceMod gamedata files
> > >      [02] Webternet (1.9.0.6282): Extension for interacting with URLs
> > >      [03] <FAILED> file "game.cstrike.ext.2.csgo.dll": Could not read sm-cstrike.games: Section declared with unknown tokens
> > >      [04] BinTools (1.9.0.6282): Low-level C/C++ Calling API
> > >      [05] SDK Tools (1.9.0.6282): Source SDK Tools
> > >      [06] Top Menus (1.9.0.6282): Creates sorted nested menus
> > >      [07] Client Preferences (1.9.0.6282): Saves client preference settings
> > >      [08] SQLite (1.9.0.6282): SQLite Driver
> > >      [09] <OPTIONAL> file "dhooks.ext.dll": No se puede encontrar el mdulo especificado.
> > >      
> > >      [10] SDK Hooks (1.9.0.6282): Source SDK Hooks
> > >      [11] Regex (1.9.0.6282): Provides regex natives for plugins
> > >      [12] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
> > >      [13] GeoIP (1.9.0.6282): Geographical IP information
> > >      [14] PTaH (1.1.0): Additional CS:GO Hooks and Natives
> > >      [15] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI
> > > ```
> > > 
> > > 
> > > its my list.
> > 
> > 
> > Your gamedata is invalid. Make sure you copy paste all the files.
> > Oh. And make sure you disable the gamedata updater temporarily by setting DisableAutoUpdate to yes in core.cfg
> 
> Modify only two files engine.csgo.txt, game.csgo.txt and core.cfg the game works. just don't lift the smx. but this does not solve my problem, I execute this "sm exts list" command again ...
> 
> REGISTRATION: [01] File "game.cstrike.ext.2.csgo.dll": Could not read sm-cstrike.games: Section declared with unknown tokens
> [02] BinTools (1.9.0.6282): C / C ++ low level calling API
> [03] SDK Tools (1.9.0.6282): Source SDK Tools
> [04] Main menus (1.9.0.6282): Create ordered nested menus
> [05] Customer preferences (1.9.0.6282): Save the customer preference settings
> [06] SQLite (1.9.0.6282): SQLite driver
> [07] file "dhooks.ext.dll": The specified module cannot be found.
> 
> [08] SDK Hooks (1.9.0.6282): Source SDK Hooks
> [09] Regex (1.9.0.6282): provides regex natives for add-ons
> [10] SteamWorks extension (1.2.3): exposes SteamWorks functions to developers
> [11] GeoIP (1.9.0.6282): IP geographic information
> [12] PTaH (1.1.0): Additional CS: GO Hooks and Natives
> [13] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI
> 
> the problem persists :(
> 
> listing error plugins: Errors:
> advancedresetscore.smx ([CS: GO] Advanced ResetScore plugin): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> deathmatch.smx (Deathmatch): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> gloves.smx (Gloves): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> kento_rankme.smx (RankMe): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> multicfg.smx (MultiCFG): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> weapons.smx (Weapons & Knives): Required extension "cstrike" file ("games / game.cstrike.ext") not running

Your issue is a botched, manual update of the gamedata files.

**Comment by gonzalopixart** [comment]
> > > > > > With these changes, another problem may be ignored. is that now certain add-ons throw the error: required extension of the file "cstrike" ("games/game.cstrike.ext any possible solution?
> > > > > > logs from my server: advancedresetscore.smx ([CS:GO] Advanced ResetScore plugin): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > > deathmatch.smx (Deathmatch): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > > gloves.smx (Gloves): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > > kento_rankme.smx (RankMe): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > > multicfg.smx (MultiCFG ): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > > weapons.smx (Weapons & Knives): Required extension "cstrike" file("games/game.cstrike.ext") not running
> > > > > 
> > > > > 
> > > > > Please do "sm exts list" for me
> > > > 
> > > > 
> > > > ```
> > > >   [01] Automatic Updater (1.9.0.6282): Updates SourceMod gamedata files
> > > >      [02] Webternet (1.9.0.6282): Extension for interacting with URLs
> > > >      [03] <FAILED> file "game.cstrike.ext.2.csgo.dll": Could not read sm-cstrike.games: Section declared with unknown tokens
> > > >      [04] BinTools (1.9.0.6282): Low-level C/C++ Calling API
> > > >      [05] SDK Tools (1.9.0.6282): Source SDK Tools
> > > >      [06] Top Menus (1.9.0.6282): Creates sorted nested menus
> > > >      [07] Client Preferences (1.9.0.6282): Saves client preference settings
> > > >      [08] SQLite (1.9.0.6282): SQLite Driver
> > > >      [09] <OPTIONAL> file "dhooks.ext.dll": No se puede encontrar el mdulo especificado.
> > > >      
> > > >      [10] SDK Hooks (1.9.0.6282): Source SDK Hooks
> > > >      [11] Regex (1.9.0.6282): Provides regex natives for plugins
> > > >      [12] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
> > > >      [13] GeoIP (1.9.0.6282): Geographical IP information
> > > >      [14] PTaH (1.1.0): Additional CS:GO Hooks and Natives
> > > >      [15] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI
> > > > ```
> > > > 
> > > > 
> > > > its my list.
> > > 
> > > 
> > > Your gamedata is invalid. Make sure you copy paste all the files.
> > > Oh. And make sure you disable the gamedata updater temporarily by setting DisableAutoUpdate to yes in core.cfg
> > 
> > 
> > Modify only two files engine.csgo.txt, game.csgo.txt and core.cfg the game works. just don't lift the smx. but this does not solve my problem, I execute this "sm exts list" command again ...
> > REGISTRATION: [01] File "game.cstrike.ext.2.csgo.dll": Could not read sm-cstrike.games: Section declared with unknown tokens
> > [02] BinTools (1.9.0.6282): C / C ++ low level calling API
> > [03] SDK Tools (1.9.0.6282): Source SDK Tools
> > [04] Main menus (1.9.0.6282): Create ordered nested menus
> > [05] Customer preferences (1.9.0.6282): Save the customer preference settings
> > [06] SQLite (1.9.0.6282): SQLite driver
> > [07] file "dhooks.ext.dll": The specified module cannot be found.
> > [08] SDK Hooks (1.9.0.6282): Source SDK Hooks
> > [09] Regex (1.9.0.6282): provides regex natives for add-ons
> > [10] SteamWorks extension (1.2.3): exposes SteamWorks functions to developers
> > [11] GeoIP (1.9.0.6282): IP geographic information
> > [12] PTaH (1.1.0): Additional CS: GO Hooks and Natives
> > [13] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI
> > the problem persists :(
> > listing error plugins: Errors:
> > advancedresetscore.smx ([CS: GO] Advanced ResetScore plugin): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> > deathmatch.smx (Deathmatch): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> > gloves.smx (Gloves): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> > kento_rankme.smx (RankMe): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> > multicfg.smx (MultiCFG): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> > weapons.smx (Weapons & Knives): Required extension "cstrike" file ("games / game.cstrike.ext") not running
> 
> Your issue is a botched, manual update of the gamedata files.

How could I solve this? sorry if i annoying

**Comment by gonzalopixart** [comment]
I will validate these changes again in my files. if you think so .. I try and confirm if the plugins work or the error persists

**Comment by gonzalopixart** [comment]
that fix solve problem

**Comment by mmendesico** [comment]
how did you solve it?

**Comment by gonzalopixart** [comment]
> I will validate these changes again in my files. if you think so .. I try and confirm if the plugins work or the error persists

that fix solve problem

**Comment by gonzalopixart** [comment]
> how did you solve it?

yes whit this commit https://github.com/alliedmodders/sourcemod/pull/1125

**Comment by fafaffff** [comment]
SetClanTag is Broken

**Comment by gonzalopixart** [comment]
> SetClanTag is Broken
 hi, What is the error log it gives you?

**Comment by gonzalopixart** [comment]
> SetClanTag is Broken

 hi, What is the error log it gives you?

**Comment by Akeno215** [comment]
HTML is broken

**Comment by XIIIG** [comment]
CS_SetClientContributionScore is broken too.

**Pull request merged**
