### PR TITLE
Update tf2.inc TFCond enums

### PR DESCRIPTION
**Pull request by Benoist3012**
I don't know the other conds before, but 114 is for the spawn outline.(added in gun mettle update).

### CODE REVIEW

**Comment by psychonic** [comment]
Thanks.

**Comment by Benoist3012** [comment]
Well I tried to find the conds before.
108 TFCond_EyeaductUnderworld,  //On set give uber to client for 2sec, on removed give overheal, uber, crits, and print a server message "%Playername% has escaped the underworld!"
109 TFCond_KingRune
110 TFCond_PlagueRune
111 TFCond_SupernovaRune
112 TFCond_Plague
113 ???
114 TFCond_SpawnOutline

**Comment by powerlord** [comment]
To be fair, 108-113 were in pull request #450 which was soft-rejected (because of the other changes I assume)

**Comment by KyleSanderson** [comment]
@powerlord you keep saying we're soft rejecting PRs when they're incomplete. As always, if something is missed, you're absolutely free to message me. However, trolling around in PRs asking why they're soft rejected when they're not functional helps no one.

I don't get it.

**Comment by psychonic** [comment]
Wtf

**Comment by powerlord** [comment]
@KyleSanderson The other PR was incomplete?  Last I checked, it had all the TFCond, TF_CUSTOM, and TF_WEAPON values that were added to the game prior to the time it was created.

No,[@asherkin's comment](https://github.com/alliedmodders/sourcemod/pull/450#discussion_r45871719) were pretty clear about why it was being soft-rejected: it added secondary names to older TFCond values.

On a side note, I rarely comment on PRs, so I'm not sure where the "you keep saying" part is coming from.

**Comment by KyleSanderson** [comment]
@powerlord below is the most obvious one. There's more from yourself on the board.
https://github.com/alliedmodders/sourcemod/pull/30#issuecomment-67018220

However, like the above comments, this doesn't belong here.

**Comment by psychonic** [comment]
@KyleSanderson please stop picking fights

**Comment by FlaminSarge** [comment]
Out of curiousity, why was this merged when it breaks consistency with the earlier 'Rune' condition names?

**Comment by Benoist3012** [comment]
Ah really?.... Oh yes I see what you mean, I'm sorry, I didn't paid attention. Perhaps I or you could fix it for me?

**Comment by asherkin** [comment]
It's about 23 days too late for that.

**Comment by FlaminSarge** [comment]
w.r.t. #450 I'll move all the old names up to the top of the list or the bottom of the list and have the names as they match the FGD/internal names separated by a few lines or something, and with that I can also add TFCond_RuneKing/etc matching the other Rune names.

I was just wondering why this got merged in the first place without anybody bringing that up.

**Pull request merged**
