### PR TITLE
TFCond Descriptions

### PR DESCRIPTION
**Pull request by Batfoxkid**
Adds comments about the conditions in tf2.inc. This is mainly for the [API](https://sm.alliedmods.net/new-api/tf2/TFCond "TFCond · tf2 · SourceMod Scripting API Reference") to show description of the condition. Just a small thing.

### CODE REVIEW

**Comment by KyleSanderson** [comment]
Where were these sourced from?

**Comment by Batfoxkid** [comment]
> Where were these sourced from?

https://wiki.teamfortress.com/wiki/Cheats#addcond
Main place and my own experience using them.

**Comment by asherkin** [comment]
I think I would prefer this without the numbers - if the numeric values are useful they should be specified as part of the enum or displayed by the doc tool. Thoughts?

**Comment by Batfoxkid** [comment]
Probably yeah, I do like some way of showing numeric values so that way for people who don't want to use the full name and instead do view_as<Enum>(#)

**Pull request merged**
