### PR TITLE
Add AddTargets* from adminmenu to Menu methodmap

### PR DESCRIPTION
**Pull request by JoinedSenses**
This change adds the AddTargets* functions to the Menu methodmap and also moves the stock functions from adminmenu.sp to menus.inc. It makes more sense that these functions are part of the base menu functionality rather than as plugin natives.

### CODE REVIEW

**Comment by JoinedSenses** [comment]
Tested with:

```
#include <sourcemod>

public void OnPluginStart() {
	RegConsoleCmd("sm_menutest1", cmdMenuTest1);
	RegConsoleCmd("sm_menutest2", cmdMenuTest2);
}

public Action cmdMenuTest1(int client, int args) {
	if (!client) {
		return Plugin_Handled;
	}

	Menu menu = new Menu(menuHandler_TestMenu);
	menu.SetTitle("Test 1");
	menu.AddTargets(client, true, true);
	menu.Display(client, 15);

	return Plugin_Handled;
}

public Action cmdMenuTest2(int client, int args) {
	if (!client) {
		return Plugin_Handled;
	}

	Menu menu = new Menu(menuHandler_TestMenu);
	menu.SetTitle("Test 2");
	menu.AddTargets2(client, COMMAND_FILTER_NO_BOTS);
	menu.Display(client, 15);

	return Plugin_Handled;
}

int menuHandler_TestMenu(Menu menu, MenuAction action, int param1, int param2) {
	switch (action) {
		case MenuAction_Select: {
			char buffer[32];
			menu.GetItem(param2, buffer, sizeof(buffer));

			int client = GetClientOfUserId(StringToInt(buffer));
			if (client) {
				PrintToChat(param1, "You selected #%s %N", buffer, client);
			}
			else {
				PrintToChat(param1, "#%s is not in game.", buffer);
			}
		}
		case MenuAction_End: {
			delete menu;
		}
	}
}```

**Comment by JoinedSenses** [comment]
Tested with:

```
#include <sourcemod>

public void OnPluginStart() {
	RegConsoleCmd("sm_menutest1", cmdMenuTest1);
	RegConsoleCmd("sm_menutest2", cmdMenuTest2);
}

public Action cmdMenuTest1(int client, int args) {
	if (!client) {
		return Plugin_Handled;
	}

	Menu menu = new Menu(menuHandler_TestMenu);
	menu.SetTitle("Test 1");
	menu.AddTargets(client, true, true);
	menu.Display(client, 15);

	return Plugin_Handled;
}

public Action cmdMenuTest2(int client, int args) {
	if (!client) {
		return Plugin_Handled;
	}

	Menu menu = new Menu(menuHandler_TestMenu);
	menu.SetTitle("Test 2");
	menu.AddTargets2(client, COMMAND_FILTER_NO_BOTS);
	menu.Display(client, 15);

	return Plugin_Handled;
}

int menuHandler_TestMenu(Menu menu, MenuAction action, int param1, int param2) {
	switch (action) {
		case MenuAction_Select: {
			char buffer[32];
			menu.GetItem(param2, buffer, sizeof(buffer));

			int client = GetClientOfUserId(StringToInt(buffer));
			if (client) {
				PrintToChat(param1, "You selected #%s %N", buffer, client);
			}
			else {
				PrintToChat(param1, "#%s is not in game.", buffer);
			}
		}
		case MenuAction_End: {
			delete menu;
		}
	}
}```

**Comment by asherkin** [comment]
Turning natives into stocks is a breaking change for existing plugins and is generally not the route we want to be going down, as it makes bug fixes in the code harder as it is embedded in every compiled plugin. These would need converting to C++ to be provided by core, which is pretty gross for this.

As an aside, any new API for this should only expose an equivalent to the more powerful `AddTargetsToMenu2`.

**Comment by Headline** [comment]
closing this as it is stale, if you’d like to reopen this pull request please address required changes and reopen it once you’re ready

thanks you!

**Pull request closed without merging**
