### PR TITLE
Upload sourcemod-latest-<os> text file when packaging.

### PR DESCRIPTION
**Pull request by psychonic**
This gives something for people scripting to look at rather than scraping our download pages. It will also make it easier for us to implement a static link that always gets the latest version of a branch.

### CODE REVIEW

**Comment by dvander** [comment]
:ship:

**Comment by asherkin** [comment]
I'm slightly worried about caching with this due to CloudFlare.

Sent from my iPhone

On 26 Oct 2015, at 18:33, Nicholas Hastings <notifications@github.com>
wrote:

This gives something for people scripting to look at rather than scraping
our download pages. It will also make it easier for us to implement a
static link that always gets the latest version of a branch.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/alliedmodders/sourcemod/pull/430
Commit Summary

   - Upload sourcemod-latest-<os> text file when packaging.

File Changes

   - *M* tools/buildbot/package.pl
   <https://github.com/alliedmodders/sourcemod/pull/430/files#diff-0> (17)

Patch Links:

   - https://github.com/alliedmodders/sourcemod/pull/430.patch
   - https://github.com/alliedmodders/sourcemod/pull/430.diff

—
Reply to this email directly or view it on GitHub
<https://github.com/alliedmodders/sourcemod/pull/430>.

**Comment by psychonic** [comment]
> I'm slightly worried about caching with this due to CloudFlare.

When testing, it was updating within seconds.

**Comment by asherkin** [comment]
The static edge cache doesn't kick in until x number of hits are made from
y different IPs.

Sent from my iPhone

On 26 Oct 2015, at 18:45, Nicholas Hastings <notifications@github.com>
wrote:

I'm slightly worried about caching with this due to CloudFlare.

When testing, it was updating within seconds.

—
Reply to this email directly or view it on GitHub
<https://github.com/alliedmodders/sourcemod/pull/430#issuecomment-151244852>
.

**Comment by psychonic** [comment]
Are we able to whitelist the files?

**Comment by asherkin** [comment]
(It doesn't block this - but we should have a PageRule on CF to always
validate against the origin)

Apologies for the multiple short messages, I am stuck on a godforsaken bus
due to a godforsaken crash on a godforsaken bridge.

Sent from my iPhone

On 26 Oct 2015, at 18:45, Nicholas Hastings <notifications@github.com>
wrote:

I'm slightly worried about caching with this due to CloudFlare.

When testing, it was updating within seconds.

—
Reply to this email directly or view it on GitHub
<https://github.com/alliedmodders/sourcemod/pull/430#issuecomment-151244852>
.

**Comment by psychonic** [comment]
Sounds good. I'll follow up with you on that later.

My actual intent wasn't even for people to use that file directly, but I suspect they still will. I'm going to have a small php branch that takes the branch as a GET var and redirects to the latest as listed in the file.

**Comment by dvander** [comment]
:bus: :bridge_at_night:

**Comment by 50Wliu** [comment]
Thanks for this.  It'll be very useful for CI servers.

**Pull request merged**
