### PR TITLE
better CBaseEntity::m_fFlags definition

### PR DESCRIPTION
**Pull request by GamerXCZ**
Previously FL_ANIMDUCKING was missing and the entire definition list was shifted by 1 after FL_DUCKING.

### CODE REVIEW

**Comment by JoinedSenses** [comment]
Hello.

Two things for ya.
Could you explain then purpose of this?
Could you fix the alignment of the defines to be consistent using spaces as they previously were?
markup_176

**Comment by sneak-it** [comment]
Along With JoinedSenses' statements, you have removed and changed some defines which will break existing plugins, how do you plan on accounting for backwards compatibility?

**Comment by GamerXCZ** [comment]
better?

**Comment by asherkin** [comment]
These are SM-internal defines, they're not directly passed to the game - this change doesn't seem correct.

**Comment by GamerXCZ** [comment]
> Toto jsou interní definice SM, nejsou přímo předávány hře – tato změna se nezdá správná.

I tested it and these definitions don't match.

If player in water player have FL_FLY flag.
When player start crouching have FL_WATERJUMP flag.
If player is BOT have flag FL_INWATER.
and more...

So mine definition is correct and SM definition is bad.

**Pull request closed without merging**
