### PR TITLE
Fix + Add missing Arabic translations

### PR DESCRIPTION
**Pull request by Rushaway**
https://github.com/orgs/alliedmodders/projects/1/views/1?pane=issue&itemId=24307177
Thanks to Arabic teachers `Skynet #2058` & `x sooonta#8948`

### CODE REVIEW

**Comment by asherkin** [comment]
Note to other reviewers: GH's UI really mangles the BIDI text here, check the files out in raw view.

**Comment by asherkin** [comment]
I think it's always going to be a pain to handle these files without a tool that can get the KV structure and escaping correct, poking them in a non-UTF-8-aware hex editor I can see a few structural problems that explain the check failure. Your average text editor unfortunately just isn't going to handle the different contexts well - some sort of JS SPA for translation editing might be a nice to have here.

**Comment by peace-maker** [comment]
We could use the [Translation Project Page](http://translator.mitchdempsey.com/sourcemod_plugins/search?utf8=%E2%9C%93&name=&tags=sourcemod&commit=Search) tool.
https://forums.alliedmods.net/showthread.php?t=203440

We'd need some way to integrate or sync the phrases, but the UI is there!

**Comment by peace-maker** [comment]
Hey @webdestroya! Are you interested in publishing the source of your translation tool? Maybe there's a nice way to integrate with this repo, so you'd still update phrases using pull requests here, but edit in the browser?

**Comment by webdestroya** [comment]
@peace-maker It's already open sourced at https://github.com/webdestroya/sourcemod-translator :) Be advised though I have not updated it in _years_ so it's really outdated.

**Comment by webdestroya** [comment]
If you are looking for a translation tool though, I do highly recommend https://crowdin.com/

**Comment by Rushaway** [comment]
I'm closing this PR. Sourcemod should maybe stop supporting AR lang if it's too complicated.

**Comment by peace-maker** [comment]
Maybe @roprop1 can help? Which editor did you use for your translation updates?

**Pull request closed without merging**
