### PR TITLE
Inauguration of SourcePawn enum structs

### PR DESCRIPTION
**Pull request by dvander**
This brings in enum struct support.

### CODE REVIEW

**Comment by dvander** [comment]
Note: This should not be merged yet. I want to make one additional syntax change that requires a & decorator on arguments, so pass-by-ref is not implicit.

**Comment by dvander** [comment]
This is ready to go.

**Comment by Headline** [comment]
We have lots of playerstate info held in the form of arrays for each property. I've added `PlayerState` and `PlayerInfo` enum structs that clean up our base plugins a little bit. Just waiting on another set of 👀 to make sure there was no mistakes

**Comment by 404UNFca** [comment]
This is the PR I've been waiting for.

**Pull request merged**
