### PR TITLE
Remove ConCommand hook clutter.

### PR DESCRIPTION
**Pull request by dvander**
This series of patches isolates ConCommand dispatch hooking to GameHooks. Unfortunately it's a little tricky to do that, because there are three different signatures for a command dispatch callback.

What I did here was add a new reference-counted class, CommandHook, which encapsulates a hook id and a callback function. SH_ADD occurs against this class, which handles the different signatures, wrapping the arguments, and dispatching to the callback. When all references to a CommandHook are gone, the hook is removed. The reference is bumped during callbacks just in case some weird re-entrancy stuff goes on.

In addition a bunch more places that used CCommand have been converted to ICommandArgs.

All in all this was a very nice simplification to ChatTriggers and I think we can use the same mechanism to move CON_COMMAND usage over to logic. It should also simplify moving ConCmdManager and ChatTriggers.

### CODE REVIEW

**Comment by KyleSanderson** [comment]
:shipit: when m_bIsINS is resolved

**Comment by dvander** [comment]
Filed PR #397 to deal with the horrible concmd cleaner code.

**Comment by dvander** [comment]
MRES_IGNORE isn't required, but it's good practice. I'll fix that.

**Comment by dvander** [comment]
Merged via command-line w/ nits fixed.

**Pull request closed without merging**
