### PR TITLE
Added more translation to basechat

### PR DESCRIPTION
**Pull request by TiBarification**
Also fixed colors, because it didn't work without `\x01` at begin of string.

### CODE REVIEW

**Comment by Bara20** [comment]
\x01 doesn't fix csgo colors. You need a space before \x01. [Take a look at this.](https://wiki.alliedmods.net/Csgo_quirks#Denoting_Text-Colors)

**Comment by psychonic** [comment]
Do other prints from SourceMod base plugins have this extra space? I would think that it should only be added for CS:GO, if at all since it will cause these specific messages to be offset from the rest of chat.

**Comment by TiBarification** [comment]
I think now it won't affect on non-csgo games.

**Comment by omar-damaj** [comment]
Has this fix been pushed yet? I am still seeing this issue on CS:GO servers. Seems like a fair fix that wont affect other games and would fix it until a better fix comes out.

**Comment by psychonic** [comment]
> Has this fix been pushed yet?

I haven't looked though the entire commit history, but judging by the PR still being "Open", no, I would assume that it hasn't been.

**Comment by omar-damaj** [comment]
I do apologize I did not check the status... Would this be possibly pushed soon? Just wondering if it would be or if there is a fix yet.

**Comment by TiBarification** [comment]
Tested on both games, tf2 and cs:go, all works fine. Ready to merge.

**Comment by GabeHirakawa** [comment]
@TiBarification I'm curious, is there a reason you changed the original prefixes from ADMINS/To ADMINS?

**Comment by psychonic** [comment]
@TiBarification did you test that the coloring works on CS:GO? I don't think that the 0xB trick has worked for a couple of years.

As @Bara noted, a space is commonly used now instead.

**Comment by Bara** [comment]
@psychonic he added a space like here: https://github.com/alliedmodders/sourcemod/pull/674/files#diff-d6b22c2d8f239d0172a347a30daf28bcR404 ?

**Comment by TiBarification** [comment]
>@TiBarification did you test that the coloring works on CS:GO?

Yes, it works fine.

>I don't think that the 0xB trick has worked for a couple of years.

Maybe it is really minor `symbol/color code`. I was guided by wiki.

**Comment by psychonic** [comment]
Wow, I totally missed that, only still seeing the 0B (which isn't needed or doing anything, but barely harming anything). Good catch. Thanks.

**Pull request merged**
