### PR TITLE
Adding gamedata library support for vphysics

### PR DESCRIPTION
**Pull request by InstantMuffin**
Kyles: Had maple syrup before but not now because I'm not eating from a plate, like some sort of wild animal.

### CODE REVIEW

**Comment by asherkin** [comment]
For the 3rd time, what's the use case for this? I don't see how this is useful without also exposing a helper to get and call functions on interfaces.

**Comment by InstantMuffin** [comment]
I intended to call some CPhysicsCollisionData functions using an sdkcall, which without this change does not work. Psychonic said I could go ahead and pr, so here it is.

**Comment by asherkin** [comment]
All the IPhysicsCollisionData functions are virtual, this is not necessary for calling them.

**Comment by KyleSanderson** [comment]
@InstantMuffin do you have a use case for this?

**Pull request closed without merging**
