### PR TITLE
Event.FireToClient fixups

### PR DESCRIPTION
**Pull request by psychonic**
This removes a couple of checks that are IMO unnecessary. See commit messages for details and reasoning.

### CODE REVIEW

**Comment by dvander** [comment]
🚢

**Comment by Benoist3012** [comment]
Funny thing is, dontbroadcast bugged me on the previous PR #505.
I got a question regarding that function, can we now hook an event with pre flag, and set the dontbroadcast boolean on true and fire to one client. Or we need to copy all the event?

**Comment by psychonic** [comment]
@Benoist3012 Yes, that was the original intent. The example code in that PR showed it working, when it really didn't. I had either missed that case in my testing, or tested before adding the handle ownership check.

**Comment by KyleSanderson** [comment]
https://github.com/alliedmodders/sourcemod/blob/0aa11374d8bdf305fae4acc4c251d7eff61a3050/core/smn_events.cpp#L135 should probably fix this up as well.

**Comment by psychonic** [comment]
@KyleSanderson I think we want to keep that check since the handle gets freed at the end of that path.

**Comment by peace-maker** [comment]
This should land in 1.8 too!

**Comment by psychonic** [comment]
What all is left holding us up from just making 1.9 the stable branch?

**Pull request merged**
