### PR TITLE
HUD is now supported on CSGO

### PR DESCRIPTION
**Pull request by kossolax**
https://forums.alliedmods.net/showthread.php?t=295215

### CODE REVIEW

**Comment by peace-maker** [comment]
Wasn't there some gotcha about mixing "game" and "engine" keys for csco?

**Comment by kossolax** [comment]
oops, you are right. It's "game" not "engine".

**Comment by psychonic** [comment]
While "engine" isn't technically correct for the functionality, it may not cause any issues, depending on whether or not CS:CO overrides the files that changed.

**Comment by kossolax** [comment]
Sadly it isn't working ingame if you use "engine", but it works with "game".
I went wrong with the online github editor, sorry about that.

**Comment by psychonic** [comment]
If that were true, there would be a ton of broken gamedata right now for csgo, and even more before we added support for csco, not to mention a ton also broken for other games.

**Comment by Accelerator74** [comment]
I confirm. With the "engine" there is no effect. Changed to "game" - everything worked.

**Comment by Bara20** [comment]
But works "games" for (cs)co servers, but I can test it later with "game" under (cs)co.

**Comment by Bara20** [comment]
Doesn't work with "csgo" as game, just with "csco". @psychonic

**Pull request merged**
