### PR TITLE
Add classic knife to CSWeaponID

### PR DESCRIPTION
**Pull request by Bara**
Instead of KNIFE_CSS i would call it WEAPON_CLASSIC, like it [Valve](http://media.steampowered.com/apps/csgo/blog/images/cs20/knife13.png) does.

#1105

### CODE REVIEW

**Comment by sneak-it** [comment]
But Valve does not call it that, it is weapon_knife_css:

Image

We should be consistent with the rest of the knife names, no? The rest of the entries utilize the items manifest names, I don't think we should change this now.

@Bara @Headline @asherkin

**Comment by Headline** [comment]
it’s now a breaking change to change the name, but I don’t think it’s a big deal

**Comment by Bara** [comment]
Breaking change from 2 days old change in a pretty new dev branch/version? 🤔

The official name is "Classic Knife" (csgo_english.txt -> "SFUI_WPNHUD_KnifeCSS") and for internal stuff (files, classname, ...) "knife_css".

**Comment by Headline** [comment]
if you updated and started using it, changing the name would break scripts, so yes unfortunately 

should be fine as-is, but if there’s a real push for this to be changed something can be worked out

**Pull request merged**
