### PR TITLE
Optional autoload extensions

### PR DESCRIPTION
**Pull request by Kxnrl**
sometimes, we don't need auto load that extension.

### CODE REVIEW

**Comment by peace-maker** [comment]
What is your use case where those extensions cause you trouble? Some extensions provide passive game fixes like fixing precaching issues in `OnMapStart` in CS:GO, so not loading them could do more harm than good.

**Comment by asherkin** [comment]
> Some extensions provide passive game fixes like fixing precaching issues in `OnMapStart` in CS:GO, so not loading them could do more harm than good.

The game support extensions are actually autoloaded by core explicitly: https://github.com/alliedmodders/sourcemod/blob/c3e6428ff7c605d85bb082dfb00fe4cdf7eb84a5/core/sourcemod.cpp#L477-L484

**Comment by Kxnrl** [comment]
> What is your use case where those extensions cause you trouble? Some extensions provide passive game fixes like fixing precaching issues in `OnMapStart` in CS:GO, so not loading them could do more harm than good.

Just make them as optinal.
I reach extension load limit.
I don't know why I can not load more then 40 extensions (windows 2016/2019).
for multi mod server, the extension list is changeable.
examples:
https://github.com/Kxnrl/Store/blob/master/store.sp#L35
https://github.com/Kxnrl/MiniGames/blob/master/MiniGames.sp#L47

**Review by peace-maker — CHANGES_REQUESTED** [review]
Not being able to load more than X extensions seems to be a bug, could you file a bug with as much info about that as you can please?

Adding the `AUTOLOAD_EXTENSIONS` guard for clientprefs seems fine, eventhough the clientprefs plugin strongly depends on the extension, so if you have that plugin loaded the extension will be loaded anyways. Since the game extensions are autoloaded automatically as asherkin pointed out, adding the guard to the cstrike and tf2 includes does nothing. Could you switch this up to only change the clientprefs include file, please?

**Review by peace-maker — APPROVED** [review]

**Pull request merged**
