### PR TITLE
Change sm_msay behavior to use GetMaxPageItems instead of hardcoded values

### PR DESCRIPTION
**Pull request by iNilo**
Fix for CS:GO not showing the sm_msay exit button

mSayPanel.CurrentKey = 10:
mSayPanel.CurrentKey = 10

mSayPanel.CurrentKey = 9:
mSayPanel.CurrentKey = 9

### CODE REVIEW

**Comment by psychonic** [comment]
Good catch on the issue. Instead of hardcoding a number, we should use the MaxMenuItems gamedata key that already exists. (That may not be the exact name)

**Comment by iNilo** [comment]
As in https://sm.alliedmods.net/new-api/menus/GetMaxPageItems ?
It is not exposed in the Panel methodmaps

**Comment by iNilo** [comment]
Implemented.

**Comment by iNilo** [comment]
Renamed PR

**Comment by psychonic** [comment]
Looks good. Thanks!

**Pull request merged**
