### PR TITLE
Add support for gamedata lookups from `soundemittersystem` library

### PR DESCRIPTION
**Pull request by Wend4r**

### CODE REVIEW

**Comment by Wend4r** [comment]
I need this changes to call `ISoundEmitterSystemBase::AddSoundsFromFile` from SourcePawn space
[soundemittersystem_test.games.txt](https://github.com/alliedmodders/sourcemod/files/8965464/soundemittersystem_test.games.txt)

**Comment by Wend4r** [comment]
It would be possible to add a native, but this seemed to me more universal.

**Comment by peace-maker** [comment]
We could just merge this until that other more generic implementation is ready? @psychonic

**Comment by psychonic** [comment]
> We could just merge this until that other more generic implementation is ready? @psychonic

That's fine.

**Review by peace-maker — APPROVED** [review]

**Comment by Wend4r** [comment]
Thanks!

**Pull request merged**
