### PR TITLE
Add Event.GetDataTypes() method

### PR DESCRIPTION
**Pull request by Wend4r**
This pull request is necessary for the possibility of iterating the parameters of the event, if the task is to log events in the SourcePawn environment and not update the valid parameters from the Wiki every time.

### CODE REVIEW

**Comment by Wend4r** [comment]
Example code
[test_event_data_types.zip](https://github.com/alliedmodders/sourcemod/files/6803108/test_event_data_types.zip)

Output
```
L 07/12/2021 - 17:22:58: [test_event_data_types.smx] Event "round_start"
Data types KeyValues:
"descriptor"
{
        "timelimit"             "3"
        "fraglimit"             "3"
        "objective"             "1"
}

L 07/12/2021 - 17:22:58: [test_event_data_types.smx] Paramenter "timelimit" is equal "999" (long)
L 07/12/2021 - 17:22:58: [test_event_data_types.smx] Paramenter "fraglimit" is equal "0" (long)
L 07/12/2021 - 17:22:58: [test_event_data_types.smx] Paramenter "objective" is equal "BOMB TARGET" (string)
```

**Comment by eyal282** [comment]
I want to add that if you must replicate an event with different parameters, this beats the updates of CSGO

**Comment by asherkin** [comment]
Have you considered parsing `modevents.res` / `gameevents.res` / `serverevents.res` directly? It seems that is all this API does under the hood - Source has always had these event descriptor files (and they're what is used to update the wiki), it looks like CS:GO has just now made them authoritative rather than advisory.

The KV structure is very simple and almost exactly mirrors the API this PR is exposing (just with readable string values rather than opaque integer identifiers), and a plugin providing a wrapping API around the res files would work for almost all Source games (just with not-guaranteed accuracy for non-CS:GO/Blade), so I think that is probably a much better path forward rather than adding this new API to SM.

https://github.com/SteamDatabase/GameTracking-CSGO/blob/ac9963b29e7d33adc190b36648f208a0b33cf20a/csgo/pak01_dir/resource/modevents.res#L25-L46

**Comment by Wend4r** [comment]
> Have you considered parsing `modevents.res` / `gameevents.res` / `serverevents.res` directly?

Yes, but I thought that it would be more convenient to use `methodmap Event`. When reading `.res` files with events, will have to search for the desired event in several KeyValues at once, and it works slowly in contrast to that game already knows in the `CGameEventDescriptor` which structures with types belong to a certain event.

**Comment by asherkin** [comment]
Thanks for the PR but I'm going to close it based on the reasoning in my previous comment. You should be able to avoid any perf impact by pre-parsing all the relevant res files (which is just what the game does) in a central plugin and offering an API (which I look forward to seeing released on the forum!)

**Comment by Wend4r** [comment]
image
I will restore the branch, because in the end it turned out that the events in these files may matches. The order of loading event files is called via `CGameEventManager`.

**Pull request closed without merging**
