### PR TITLE
Fix wrong formating to "Vote Delay Minutes" when delay above 60s

### PR DESCRIPTION
**Pull request by PlayBoy31**
See https://github.com/alliedmodders/sourcemod/issues/1007

### CODE REVIEW

**Comment by asherkin** [comment]
Unless I'm being silly, shouldn't the `%` just be `/` here?

**Comment by KyleSanderson** [comment]
We still want it to wrap around 60 as that's our current unit of time. FormatTime is likely the most correct fix here.

**Comment by PlayBoy31** [comment]
FormatTime is not appropriate and a time stamp must be used

Some solutions:
1) limit sm_vote_delay to 3600 seconds to cover the only corner case
2) or move function `int FormatTimeDuration(char[] buffer, int maxlen, int time)` from `nextmap.sp` to another place (maybe in `timers.inc` as stock) and use `FormatTimeDuration` to format the delay on basevotes.sp and funvotes.sp

**Comment by PlayBoy31** [comment]
> 
> 
> Unless I'm being silly, shouldn't the `%` just be `/` here?

Ok corrected as your suggest

**Pull request merged**
