### PR TITLE
Fix more sdktools crash on 64 bits

### PR DESCRIPTION
**Pull request by bottiger1**
Found some more pointer arithmetic in sdktools assuming 32bits.

### CODE REVIEW

**Comment by bottiger1** [comment]
> is there still - 4 to get IClient?

I did grep "+ 4" and "- 4" in the sdktools directory. I did not check any other directory.

**Comment by asherkin** [comment]
While I understand it seems to be the same in practice, `sizeof(intptr_t)` feels wrong here - I would expect `sizeof(void *)` for this usage.

**Comment by assyrianic** [comment]
> While I understand it seems to be the same in practice, `sizeof(intptr_t)` feels wrong here - I would expect `sizeof(void *)` for this usage.

Any particular reason why? Most of the code itself is already using `[u]intptr_t` anyway.

**Comment by asherkin** [comment]
> Any particular reason why? Most of the code itself is already using `[u]intptr_t` anyway.

Which is obviously correct for the math, but the spec only appears to guarantee `sizeof(intptr_t) >= sizeof(void *)` - and what we want here is the size of a (specific) pointer, not the size of the integer type to represent any arbitrary pointer.

**Comment by bottiger1** [comment]
We don't need to have a long discussion about this. If you want to change it to void* for a hypothetical architecture where the fastest integer type is somehow larger than the pointer type, it doesn't matter to me. I just want these crashes gone.

**Comment by dvander** [comment]
static_assert() that your intention is true and move on, I say.

**Review by psychonic — APPROVED** [review]

**Pull request merged**
