### PR TITLE
Update CoreConfig.cpp

### PR DESCRIPTION
**Pull request by Bluscream**
# <a style="font-size:50px" href="https://github.com/alliedmodders/sourcemod/pull/1119/files">Click me</a></font>

### CODE REVIEW

**Comment by Bluscream** [comment]
This pull request is licensed under the [Do What the Fuck You Want to Public License](http://www.wtfpl.net/) so you're free to resubmit it with a proper description if you feel like it.

**Comment by dvander** [comment]
Patch looks good, thanks for the change! But WTFPL is not a real license and its compatibility with GPL is doubtful.

**Comment by KyleSanderson** [comment]
@Bluscream when you're ready to relicense the patch to GPL we'd be happy to take the enhancement. Ping us when you're ready :)

**Comment by Bluscream** [comment]
Or you just rewrite one line of code yourself ;)

**Pull request closed without merging**
