### PR TITLE
Update SourcePawn.

### PR DESCRIPTION
**Pull request by dvander**

### CODE REVIEW

**Comment by Accelerator74** [comment]
New sourcemod compiler is fully broken 😦
> L 11/01/2021 - 08:43:20: [SM] Exception reported: Invalid memory access

Many errors in logs from all plugins and constant server crashes.

**Comment by dvander** [comment]
Can you give me some steps to reproduce?

**Comment by Accelerator74** [comment]
I even know how to show  example for you. The server just randomly swears at various functions, including various Handle and after a while crash. However, everything works correctly on the old compiler. I will try to throw in an example code for you a little later.

**Comment by dvander** [comment]
Any specific plugins that cause an error?

**Comment by Accelerator74** [comment]
Example crash
```
#0  0xf7ddf4b6 in ?? () from /lib32/libc.so.6
[Current thread is 1 (Thread 0xf7f66a80 (LWP 107342))]
(gdb) bt
#0  0xf7ddf4b6 in ?? () from /lib32/libc.so.6
#1  0xefbcb15a in SplitString(SourcePawn::IPluginContext*, int const*) () from /home/server/left4dead2/addons/sourcemod/bin/sourcemod.logic.so
#2  0xdc62bc82 in ?? ()
#3  0xdc62adcd in ?? ()
#4  0xeec7c06f in ?? ()
#5  0xefabc8b8 in sp::Environment::Invoke(sp::PluginContext*, ke::RefPtr<sp::MethodInfo> const&, int*) () from /home/server/left4dead2/addons/sourcemod/bin/sourcepawn.jit.x86.so
#6  0xefac30a8 in sp::PluginContext::Invoke(unsigned int, int const*, unsigned int, int*) () from /home/server/left4dead2/addons/sourcemod/bin/sourcepawn.jit.x86.so
#7  0xefac82b1 in sp::ScriptedInvoker::Invoke(int*) () from /home/server/left4dead2/addons/sourcemod/bin/sourcepawn.jit.x86.so
#8  0xefac7fef in sp::ScriptedInvoker::Execute(int*) () from /home/server/left4dead2/addons/sourcemod/bin/sourcepawn.jit.x86.so
#9  0xefbbce50 in non-virtual thunk to TimerNatives::OnTimer(SourceMod::ITimer*, void*) () from /home/server/left4dead2/addons/sourcemod/bin/sourcemod.logic.so
#10 0xefd1ca79 in TimerSystem::RunFrame() () from /home/server/left4dead2/addons/sourcemod/bin/sourcemod.2.l4d2.so
#11 0xefd1c9b0 in TimerSystem::GameFrame(bool) () from /home/server/left4dead2/addons/sourcemod/bin/sourcemod.2.l4d2.so
#12 0xefd35379 in __SourceHook_FHCls_IServerGameDLLGameFramefalse::CMyDelegateImpl::Call(bool) () from /home/server/left4dead2/addons/sourcemod/bin/sourcemod.2.l4d2.so
#13 0xefd34eb1 in __SourceHook_FHCls_IServerGameDLLGameFramefalse::Func(bool) () from /home/server/left4dead2/addons/sourcemod/bin/sourcemod.2.l4d2.so
```

**Comment by Accelerator74** [comment]
There are also other errors in plugins that are not available with the old compiler, but so far it is difficult to save them, because the server crashes at absolutely chaotic moments.

**Comment by dvander** [comment]
Thanks, I'll revert this change if I can't find any root cause soon.

**Comment by asherkin** [comment]
Are you using both an up to date compiler and SM version, or using the new compiler with an old SP runtime?

Are you using a modified or patched SP runtime?

**Comment by Accelerator74** [comment]
Original compiler with original SourceMod binary. Compiller version is equal sm version.

**Comment by asherkin** [comment]
Addie caught this with a stock plugin, https://crash.limetech.org/l2t4boh5bcws, crashed in `adminhelp.smx::HelpCmd`.

**Comment by dvander** [comment]
Thanks, I can reproduce this in mock srcds.

**Pull request merged**
